# Generated by Django 6.0 on 2026-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("eastern_lake_superior", "Eastern Lake Superior"),
                            ("western_lake_superior", "Western Lake Superior"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("detailed", "Detailed"),
                            ("waves", "Waves"),
                            ("extended", "Extended"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("published_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "category",
                    models.CharField(choices=[("marine", "Marine")], max_length=20),
                ),
                ("summary", models.TextField()),
                ("link", models.URLField(max_length=255)),
                ("weather_canada_id", models.CharField(max_length=255)),
            ],
        ),
    ]
