# Generated by Django 6.0 on 2026-01-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherreport",
            name="region",
            field=models.CharField(
                choices=[
                    ("eastern_lake_superior", "Eastern Lake Superior"),
                    ("western_lake_superior", "Western Lake Superior"),
                    ("undefined", "Undefined"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="weatherreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("detailed", "Detailed"),
                    ("waves", "Waves"),
                    ("extended", "Extended"),
                    ("undefined", "Undefined"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="weatherreport",
            constraint=models.UniqueConstraint(
                fields=("region", "report_type", "published_time"),
                name="unique_region_and_report_type",
            ),
        ),
    ]
