# Generated by Django 4.2 on 2026-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_tracker", "0002_alter_weatherreport_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherreport",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="weatherreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("detailed", "Detailed"),
                    ("waves", "Waves"),
                    ("extended", "Extended"),
                    ("FREEZING_SPRAY_WARNING", "Freezing Spray Warning"),
                    ("GALE_WARNING", "Gale Warning"),
                    ("undefined", "Undefined"),
                ],
                max_length=40,
            ),
        ),
    ]
