# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_tracker", "0003_alter_weatherreport_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherreport",
            name="wind_direction",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="weatherreport",
            name="wind_speed_knots",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherreport",
            name="max_wave_height_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherreport",
            name="visibility_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
