# Generated by Django 4.2 on 2026-02-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_tracker", "0004_add_summary_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherreport",
            name="category",
            field=models.CharField(
                choices=[("marine", "Marine"), ("air_quality", "Air Quality")],
                max_length=20,
            ),
        ),
    ]
