# Generated by Django 4.2 on 2026-02-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_tracker", "0005_alter_weatherreport_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherreport",
            name="breaking_db_change",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
